travis:
  secure:
    BINSTAR_TOKEN: pvkPqngsHl9v5Tdnmv2kkZ/s6jYw6jt1eUnta90iP4I3D5VcQdQqVhiIetawpcRxo/POK5paVa3tO+ODcuAvcLp2gx5RsqG8WLTyxT67H7umahR14Q83W31bZOv92UFrwG7fECR9BiQkZSC+qahNt5fbP2fFnauu+tE/f9XXgP3wNi3/qH5YsUSOZP0yy/eDohDvdeFjAMgHW/AC9oAQtDtzfb7UHMfDkOjSibXF3fSyO7PDV3jo0tfl1otZfgI3l1AUlJHxPcd4KTcQvr4dheoc5AaDgTD01OUgbswyQyw6e2DieZnr2KcffYB9Ftv7oYnMx+RGN+uE6tYRORMek9l9Ya0818LQBp6r6cJ+4pV+omj8afsDixVlfYzDLszN+CNUS2tWOMHnJFSIDSTrLKF8OEKMCuvZKBX2CaNIqdg/qnAahAWy1eG56k7xgyaTIRydm/fyRORDLN8d8/cSzSkkoIzmA+17vxSGHfciyuLHgzb13jAzBVjA7ayzdtCIm/puvd58mmc6zFZQvIN/RDCSa1+hIixSPAS+N0hurRYcWcQXkc1DSxLd95orZdijo+kvwa27Cp2zu9PlxrfmQdhF1u34HG3i9jufaD/8on8p6Ux/tZELvhqtwthPg4to0VXJcOu1HjyPJLB8i1qPeDxzpKnnLTGol+Y9Z/hoZ0U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
